/**
 * ClawSQL - Core Types and Models
 *
 * TypeScript interfaces and enums converted from Python dataclasses.
 */

// =============================================================================
// Enums
// =============================================================================

/** MySQL instance role in the cluster */
export enum InstanceRole {
  PRIMARY = 'primary',
  REPLICA = 'replica',
  UNKNOWN = 'unknown',
}

/** MySQL instance operational state */
export enum InstanceState {
  ONLINE = 'online',
  OFFLINE = 'offline',
  RECOVERING = 'recovering',
  FAILED = 'failed',
  MAINTENANCE = 'maintenance',
}

/** Health status for instances and clusters */
export enum HealthStatus {
  HEALTHY = 'healthy',
  DEGRADED = 'degraded',
  UNHEALTHY = 'unhealthy',
  UNKNOWN = 'unknown',
}

/** Alert severity levels */
export enum AlertSeverity {
  INFO = 'info',
  WARNING = 'warning',
  CRITICAL = 'critical',
}

/** Failover operation states */
export enum FailoverState {
  IDLE = 'idle',
  DETECTING = 'detecting',
  CANDIDATE_SELECTION = 'candidate_selection',
  PROMOTING = 'promoting',
  RECONFIGURING = 'reconfiguring',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

/** Types of failures that can be detected */
export enum FailureType {
  PRIMARY_UNREACHABLE = 'primary_unreachable',
  PRIMARY_NOT_WRITING = 'primary_not_writing',
  REPLICATION_STOPPED = 'replication_stopped',
  REPLICATION_LAG_HIGH = 'replication_lag_high',
  DISK_FULL = 'disk_full',
  MEMORY_EXHAUSTED = 'memory_exhausted',
}

/** Replication mode for cluster templates */
export enum ReplicationMode {
  ASYNC = 'async',
  SEMI_SYNC = 'semi-sync',
  GROUP_REPLICATION = 'group-replication',
}

/** Provisioning status for template-based clusters */
export enum ProvisionStatus {
  PENDING = 'pending',
  PROVISIONING = 'provisioning',
  READY = 'ready',
  FAILED = 'failed',
}

// =============================================================================
// Interfaces
// =============================================================================

/** Represents a discovered MySQL instance */
export interface MySQLInstance {
  host: string;
  port: number;
  serverId?: number;
  role: InstanceRole;
  state: InstanceState;
  version?: string;
  replicationLag?: number;
  lastSeen: Date;
  clusterId?: string;
  labels: Record<string, string>;
  extra: Record<string, unknown>;
}

/** Represents a MySQL cluster topology */
export interface MySQLCluster {
  clusterId: string;
  name: string;
  primary?: MySQLInstance;
  replicas: MySQLInstance[];
  createdAt: Date;
  updatedAt: Date;
  description?: string;
}

/** Failover operation record */
export interface FailoverOperation {
  operationId: string;
  clusterId: string;
  oldPrimaryId: string;
  newPrimaryId?: string;
  state: FailoverState;
  startedAt?: Date;
  completedAt?: Date;
  steps: string[];
  error?: string;
  manual: boolean;
  reason: string;
  triggeredBy?: string;
}

/** Failure event detected by the system */
export interface FailureEvent {
  eventId: string;
  failureType: FailureType;
  instanceId: string;
  clusterId: string;
  detectedAt: Date;
  confirmed: boolean;
  confirmationCount: number;
  details: Record<string, unknown>;
}

/** Alert generated by the monitoring system */
export interface Alert {
  alertId: string;
  severity: AlertSeverity;
  instanceId?: string;
  clusterId?: string;
  message: string;
  details: Record<string, unknown>;
  createdAt: Date;
  acknowledged: boolean;
  acknowledgedAt?: Date;
  acknowledgedBy?: string;
}

/** Instance metrics collected from MySQL */
export interface InstanceMetrics {
  instanceId: string;
  timestamp: Date;
  replicationLagSeconds?: number;
  replicationIoRunning: boolean;
  replicationSqlRunning: boolean;
  connectionsCurrent: number;
  connectionsMax: number;
  queriesPerSecond: number;
  innodbBufferPoolHitRate: number;
  uptimeSeconds: number;
  diskUsagePercent?: number;
  memoryUsagePercent?: number;
}

/** Health check result */
export interface HealthCheckResult {
  checkName: string;
  status: HealthStatus;
  value: number;
  message: string;
  threshold?: number;
}

/** Topology template for cluster provisioning */
export interface TopologyTemplate {
  templateId: string;
  name: string;
  description?: string;
  primaryCount: number;
  replicaCount: number;
  replicationMode: ReplicationMode;
  settings?: {
    maxReplicationLag?: number;
    failoverPriority?: 'lowest-lag' | 'highest-binlog';
  };
  createdAt: Date;
  updatedAt: Date;
}

/** Cluster metadata for provisioned clusters */
export interface ClusterMetadata {
  clusterId: string;
  templateId?: string;
  assignedPort?: number;
  writerHostgroup?: number;
  readerHostgroup?: number;
  provisionStatus: ProvisionStatus;
  createdAt: Date;
  updatedAt: Date;
}

/** Provisioned instance for template-based clusters */
export interface ProvisionedInstance {
  clusterId: string;
  host: string;
  port: number;
  role: 'primary' | 'replica';
  sequence: number;
  provisionedAt: Date;
}

// =============================================================================
// Helper Functions
// =============================================================================

/** Create a unique instance ID from host and port */
export function createInstanceId(host: string, port: number): string {
  return `${host}:${port}`;
}

/** Create a default MySQL instance */
export function createMySQLInstance(
  host: string,
  port: number,
  overrides?: Partial<MySQLInstance>
): MySQLInstance {
  return {
    host,
    port,
    serverId: overrides?.serverId,
    role: overrides?.role ?? InstanceRole.UNKNOWN,
    state: overrides?.state ?? InstanceState.OFFLINE,
    version: overrides?.version,
    replicationLag: overrides?.replicationLag,
    lastSeen: overrides?.lastSeen ?? new Date(),
    clusterId: overrides?.clusterId,
    labels: overrides?.labels ?? {},
    extra: overrides?.extra ?? {},
  };
}

/** Create a default MySQL cluster */
export function createMySQLCluster(
  clusterId: string,
  name: string,
  overrides?: Partial<MySQLCluster>
): MySQLCluster {
  return {
    clusterId,
    name,
    primary: overrides?.primary,
    replicas: overrides?.replicas ?? [],
    createdAt: overrides?.createdAt ?? new Date(),
    updatedAt: overrides?.updatedAt ?? new Date(),
    description: overrides?.description,
  };
}

/** Check if instance is a primary */
export function isPrimary(instance: MySQLInstance): boolean {
  return instance.role === InstanceRole.PRIMARY;
}

/** Check if instance is a replica */
export function isReplica(instance: MySQLInstance): boolean {
  return instance.role === InstanceRole.REPLICA;
}

/** Check if instance is online */
export function isOnline(instance: MySQLInstance): boolean {
  return instance.state === InstanceState.ONLINE;
}

/** Check if instance is healthy */
export function isHealthy(instance: MySQLInstance): boolean {
  return instance.state === InstanceState.ONLINE && instance.role !== InstanceRole.UNKNOWN;
}

/** Get instance count for a cluster */
export function getInstanceCount(cluster: MySQLCluster): number {
  let count = 0;
  if (cluster.primary) count += 1;
  count += cluster.replicas.length;
  return count;
}

/** Get healthy instance count for a cluster */
export function getHealthyCount(cluster: MySQLCluster): number {
  let count = 0;
  if (cluster.primary && isHealthy(cluster.primary)) count += 1;
  count += cluster.replicas.filter(isHealthy).length;
  return count;
}

/** Get overall cluster health status */
export function getClusterHealthStatus(cluster: MySQLCluster): HealthStatus {
  const instanceCount = getInstanceCount(cluster);
  if (instanceCount === 0) return HealthStatus.UNKNOWN;

  const healthyRatio = getHealthyCount(cluster) / instanceCount;

  if (healthyRatio >= 1.0) return HealthStatus.HEALTHY;
  if (healthyRatio >= 0.5) return HealthStatus.DEGRADED;
  return HealthStatus.UNHEALTHY;
}

/** Create a topology template */
export function createTopologyTemplate(
  templateId: string,
  overrides?: Partial<TopologyTemplate>
): TopologyTemplate {
  return {
    templateId,
    name: overrides?.name ?? 'unnamed',
    description: overrides?.description,
    primaryCount: overrides?.primaryCount ?? 1,
    replicaCount: overrides?.replicaCount ?? 2,
    replicationMode: overrides?.replicationMode ?? ReplicationMode.ASYNC,
    settings: overrides?.settings,
    createdAt: overrides?.createdAt ?? new Date(),
    updatedAt: overrides?.updatedAt ?? new Date(),
  };
}

/** Create cluster metadata */
export function createClusterMetadata(
  clusterId: string,
  overrides?: Partial<ClusterMetadata>
): ClusterMetadata {
  return {
    clusterId,
    templateId: overrides?.templateId,
    assignedPort: overrides?.assignedPort,
    writerHostgroup: overrides?.writerHostgroup,
    readerHostgroup: overrides?.readerHostgroup,
    provisionStatus: overrides?.provisionStatus ?? ProvisionStatus.PENDING,
    createdAt: overrides?.createdAt ?? new Date(),
    updatedAt: overrides?.updatedAt ?? new Date(),
  };
}

// =============================================================================
// Merged Cluster View Types (Orchestrator + ProxySQL)
// =============================================================================

/** Instance with merged Orchestrator and ProxySQL data */
export interface MergedInstanceInfo {
  host: string;
  port: number;
  state: InstanceState;
  role: InstanceRole;
  version?: string;
  serverId?: number;
  replicationLag?: number;
  /** ProxySQL hostgroup (10=writer, 20=reader) */
  hostgroup?: number;
  /** ProxySQL server status (ONLINE, OFFLINE_SOFT, etc.) */
  proxysqlStatus?: string;
  /** Active connections from ProxySQL connection pool */
  connections?: number;
}

/** ProxySQL endpoint information */
export interface ProxySQLEndpoint {
  host: string;
  port: number;
}

/** Hostgroup routing configuration */
export interface HostgroupConfig {
  writer: number;
  reader: number;
}

/** Sync warning type */
export interface SyncWarning {
  /** Warning type: missing_in_proxysql, wrong_hostgroup, unknown_in_orchestrator */
  type: 'missing_in_proxysql' | 'wrong_hostgroup' | 'unknown_in_orchestrator';
  /** Instance identifier */
  instance: string;
  /** Human-readable description */
  message: string;
}

/** Merged cluster view combining Orchestrator topology with ProxySQL routing */
export interface MergedClusterView {
  /** Cluster identifier from Orchestrator */
  clusterId: string;
  /** User-friendly cluster name */
  displayName: string;
  /** ProxySQL endpoint for client connections */
  endpoint?: ProxySQLEndpoint;
  /** Hostgroup routing configuration */
  hostgroups?: HostgroupConfig;
  /** Primary instance with merged data */
  primary: MergedInstanceInfo | null;
  /** Replica instances with merged data */
  replicas: MergedInstanceInfo[];
  /** Overall cluster health */
  health: HealthStatus;
  /** Sync warnings when ProxySQL and Orchestrator are out of sync */
  syncWarnings?: SyncWarning[];
}